### ISSUE TITLE
lua里面的Launcher案例运行不起来

### ISSUE THREAD

**Issue by Icereek** [cocowolf/loxodon-framework#14]
local window = locator:LoadWindow(winContainer, "LuaUI/Startup/Startup")
window:Create() --创建窗口

create()方法报错
stack traceback:
	[C]: in method 'Create'
	[string "Launcher(Launcher)"]:51: in function <[string "Launcher(Launcher)"]:34>
XLua.LuaEnv.ThrowExceptionFromError (System.Int32 oldTop) (at Assets/XLua/Src/LuaEnv.cs:441)

请问是什么情况？

**Comment by cocowolf** [comment]
你没好好看安装步骤的文档，重新读一下XLUA插件的安装步骤。我重点在文档中说明了原因。我的FAQ和XLUA的FAQ都有原因和解决方法。

**Comment by Icereek** [comment]
安装步骤和FAQ都看了，设置了.NET 4.x"，而且没有生成lua代码，这个launcher的create还是报错。但是lua案例里面的其他例子都没有问题。我使用的xlua版本是2.1.15，unity版本是2019.3。

**Comment by cocowolf** [comment]
你加QQ群吧，截图log我看看，2.1.15我没试过
