### ISSUE TITLE
示例代码在u3d 2018上报错

### ISSUE THREAD

**Issue by 5941120** [cocowolf/loxodon-framework#2]
调用堆栈：
NotSupportedException: Expressions of type System.Delegate are not supported.
Loxodon.Framework.Binding.Paths.PathParser.Parse (System.Linq.Expressions.Expression expression, Loxodon.Framework.Binding.Paths.Path path) (at Assets/LoxodonFramework/Scripts/Framework/Binding/Paths/PathParser.cs:134)
Loxodon.Framework.Binding.Paths.PathParser.Parse (System.Linq.Expressions.LambdaExpression expression) (at Assets/LoxodonFramework/Scripts/Framework/Binding/Paths/PathParser.cs:40)
Loxodon.Framework.Binding.Builder.BindingBuilder`2[TTarget,TSource].To (System.Linq.Expressions.Expression`1[TDelegate] path) (at Assets/LoxodonFramework/Scripts/Framework/Binding/Builder/BindingBuilder.cs:105)
Loxodon.Framework.Tutorials.DatabindingForAsyncLoadingSpriteExample.Start () (at Assets/LoxodonFramework/Tutorials/Scripts/DatabindingForAsyncLoadingSpriteExample.cs:53)

![image](https://user-images.githubusercontent.com/8486251/62118224-e0cd7580-b2ef-11e9-8681-93519e9fb0e8.png)

**Comment by cocowolf** [comment]
已修复！
